name: Reusable Workflow
on: 
  workflow_call:
    inputs:
      my_arg_1:
        description: this is my arg
        required: false
        default: this is the default
        type: string

jobs:
    my_common_reusable_job:
        runs-on: ubuntu-latest
        steps:
          - name: Some Dummy Step
            run: |
              echo "Running some dummy step: ${{ inputs.my_arg_1 }}"

