name: Reusable Workflow
on: workflow_call

jobs:
    my_common_reusable_job:
        runs-on: ubuntu-latest
        steps:
          - name: Some Dummy Step
            run: echo "Running some dummy step"

