name: My Artifacts
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name: clone the repo
            uses: actions/checkout@v4
          - name: install python
            uses: actions/setup-python@v5
            with:
              python-version: '3.10' 
          - name: Install Poetry
            uses: snok/install-poetry@v1
            with:
              virtualenvs-create: false
          - name: Install Dep
            run: poetry install
          - name: Run Tests
            run: pytest --rootdir=.

    build_and_upload_artifcats:
        needs: test
        outputs:
            my_sha1: ${{ steps.my_id.outputs.my_sha }}
        runs-on: ubuntu-latest
        steps:
            - name: clone the repo
              uses: actions/checkout@v4
            - name: install python
              uses: actions/setup-python@v5
              with:
                python-version: '3.10'
            - name: install Poetry
              uses: snok/install-poetry@v1
              with:
                virtualenvs-create: false
            - name: install Dep
              run: poetry install
            - name: build
              run: poetry build

            - name: get_whl_sha
              id: my_id
              run: echo my_sha=`find dist/*.whl -type f -execdir sha256sum '{}' ';'|awk '{print $1}'` >> "$GITHUB_OUPUT"
            
            - name: upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: dist_folder
                path: | # this is for multiple options
                  dist 
                  pyproject.toml
                  poetry.lock



    using_outputs:
        needs: build_and_upload_artifcats
        runs-on: ubuntu-latest        
        steps:
            - name: download artifacts
              uses: actions/download-artifact@v4
              with:
                name: dist_folder
            - name: show content
              run: ls -lah
            - name: output filenames
              run: echo "${{ needs.build_and_upload_artifcats.outputs.my_sha1 }}"
            

